name = "typyn-docs"
compatibility_date = "2025-10-23"

# This tells Cloudflare Pages where the built static files are
pages_build_output_dir = "docs/docs.vitepress/dist"

# Optional environment variables
[vars]
NODE_VERSION = "22.16.0"
PNPM_VERSION = "10.18.3"
